### ISSUE TITLE
进不去系统界面

### ISSUE THREAD

**Issue by seklure** [tangxiaofeng7/XScan#2]
![image](https://user-images.githubusercontent.com/45745859/158332993-a02e7589-d6b2-4062-9b9e-fd85ccb6e456.png)
![image](https://user-images.githubusercontent.com/45745859/158333042-a1f982dd-97e2-4ba8-a2ff-b6c6970097b6.png)

**Comment by tangxiaofeng7** [comment]
看了下，原因是打包的前端过大没有完整的传到github上，稍等下，我看看怎么解决

**Comment by tangxiaofeng7** [comment]
已解决
